# Generated by Django 5.2.7 on 2025-10-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="type",
            field=models.CharField(
                choices=[
                    ("Tennis", "Tennis"),
                    ("Badminton", "Badminton"),
                    ("Basket", "Basket"),
                    ("Sepak Bola", "Sepak Bola"),
                    ("Mini Soccer", "Mini Soccer"),
                    ("Futsal", "Futsal"),
                    ("Billiard", "Billiard"),
                    ("Tenis Meja", "Tenis Meja"),
                    ("Volly Ball", "Volly Ball"),
                ],
                default="Tennis",
                max_length=20,
            ),
        ),
    ]
