# Generated by Django 5.2.7 on 2025-10-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_venue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date_paid",
            field=models.DateField(blank=True, null=True),
        ),
    ]
